version: "3.3"
volumes:
  data:
    driver: local
  filestore:
    driver: local
services:
  dbmrv:
    container_name: dbmrv
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: "<ANY PASSWORD>"
      POSTGRES_USER: root
      PGPORT: 5433
      PSQL_USERNAME: root
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/data/postgres
  migration:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    depends_on:
      - dbmrv
      - national
    command: ['yarn', 'migration:run']
    environment:
      DB_HOST: dbmrv
      DB_PORT: 5433
      DB_USER: root
      DB_PASSWORD: "<ANY PASSWORD>"
      DB_NAME: "carbondev"
  national:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "9000:3000"
    depends_on:
      - dbmrv
    environment:
      DB_HOST: dbmrv
      DB_USER: root
      DB_PASSWORD: "<ANY PASSWORD>"
      RUN_MODULE: national-api
      rootEmail: <ROOT EMAIL>
      systemCountryCode: "NG"
      name: "Antactic Region"
      IS_EMAIL_DISABLED: "true"
      ASYNC_OPERATIONS_TYPE: Database
      HOST: "http://localhost:3030"
      DOMAIN_MAP: "true"
      EXPIRES_IN: "7200"
      DB_PORT: "5433"
      DB_NAME: "carbondev"
      NODE_ENV: 'dev'
      FILE_SERVICE: local
      DISABLE_LOW_PRIORITY_EMAIL: "true"
      SYSTEM_TYPE: CARBON_TRANSPARENCY_SYSTEM  
      BACKEND_HOST: http://localhost:9000
      SYSTEM_NAME: National NDC Transparency System
    volumes:
      - filestore:/app/backend/services/public
      - ./users.csv:/app/backend/services/users.csv
      - ./organisations.csv:/app/backend/services/organisations.csv
  stats:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "9100:3100"
    depends_on:
      - dbmrv
      - national
    environment:
      DB_HOST: dbmrv
      DB_USER: root
      DB_PASSWORD: "<ANY PASSWORD>"
      RUN_PORT: 3100
      RUN_MODULE: analytics-api
      DOMAIN_MAP: "true"
      DB_PORT: "5433"
      DB_NAME: "carbondev"
      NODE_ENV: 'dev'
      FILE_SERVICE: local
  async-operations-handler:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    depends_on:
      - dbmrv
      - national
    environment:
      DB_HOST: dbmrv
      DB_USER: root
      DB_PASSWORD: "<ANY PASSWORD>"
      RUN_MODULE: async-operations-handler
      SMTP_ENDPOINT: email-smtp.us-east-1.amazonaws.com
      SMTP_PASSWORD: ""
      SMTP_USERNAME: AKIAUMXKTXDJPDYDJ76J
      IS_EMAIL_DISABLED: "true"
      ASYNC_OPERATIONS_TYPE: Database
      DB_PORT: "5433"
      DB_NAME: "carbondev"
      NODE_ENV: 'dev'
      FILE_SERVICE: local
      DISABLE_LOW_PRIORITY_EMAIL: "true"
      SYSTEM_TYPE: CARBON_TRANSPARENCY_SYSTEM
      BACKEND_HOST: http://localhost:9000
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        PORT: 3030
        REACT_APP_BACKEND: http://localhost:9000
        REACT_APP_STAT_URL: http://localhost:9100
        REACT_APP_COUNTRY_NAME: "Antarctic Region"
    ports:
      - "9030:3030"
    depends_on:
      - dbmrv
      - national
